export const translations = {
  en: {
    language: "EN",
    nav: { dashboard: "Dashboard", about: "About", project: "Project", skills: "Skills", contact: "Contact", language: "Language" },
    hero: { availability: "Open to opportunities", intro: "Fresh graduate from", introAfter: ". I build production full-stack web applications and integrate agentic AI systems that ship to real users like POS System Website, content agents with human approval gate (telegram), chatbots, and many more", viewProjects: "View projects", getInTouch: "Get in touch", projectsFinished: "projects finished", providers: "LLM providers integrated", thesis: "Thesis validation" },
    about: { label: "About", title: "Builder mindset, operator experience.", p1: "Having operated an F&B business from 2021 to the present (2026) while building software, I’ve learned that business operations and software engineering share the same core principle: ", p1Strong: "ship it, measure it, iterate it.", p2: "A graduate of Information Technology (GPA 3.56/4.00) with strong analytical and systematic thinking skills. Experienced in building full-stack web applications and integrating AI/LLM into production systems using Node.js, React, Python, REST APIs, and many more. A fast learner who is adaptable with proven ability to manage projects independently from concept to deployment. Highly motivated to continue developing, confident that my combination of technical skills and hands-on project experience makes me ready to make a real contribution as a Full-Stack Developer, Web Developer, or AI Engineer in a professional work environment.", p3Before: "I think in systems. Every feature I build is a function, every function is a tool, every tool connects to a real action. That's what ", p3After: " means in practice." },
    projects: { label: "Selected work", titleBefore: "Practical solutions,", titleAfter: "built to solve real problems.", allRepos: "all repos", all: "All Projects", ai: "AI Agent & Automation", web: "Web Development", readMore: "Read More", viewPicture: "View the picture", photos: "Photos" },
    skills: { label: "Stack", title: "Tools, not toys.", desc: "Technologies and frameworks I use to build functional AI integration system & web applications to solve real-world problems.", tech: "Tech stack", capabilities: "Technical Capabilities & AI Integration", focus: "Current focus", focusText: "Building autonomous AI agents with Human-in-the-Loop approval, web development, frontend development, Structured RAG, and multi-tool function calling. Currently exploring LangGraph multi-agent orchestration and expanding WhatsApp & POS automation into scalable AI workflows." },
    contact: { label: "Get in touch", title: "Have a system to build?", desc: "Open to full-time roles in AI engineering, full-stack development, or contract work on agentic systems.", whatsapp: "Chat on WhatsApp", or: "or use the form below", name: "Name", namePlaceholder: "Your name", email: "Email", message: "Message", messagePlaceholder: "Send me a message about anything...", send: "Send message", reply: "Replies within 24h · Yogyakarta, GMT+7" },
    modal: { liveDemo: "Live Demo", close: "Close modal", previous: "Previous screenshot", next: "Next screenshot", highlights: "Highlights & Implementation:" },
    footer: { description: "Building production-grade web apps and agentic AI systems. Open to opportunities.", navigate: "Navigate", connect: "Connect", status: "Open to opportunities" }
  },
  id: {
    language: "ID",
    nav: { dashboard: "Beranda", about: "Tentang", project: "Proyek", skills: "Keahlian", contact: "Kontak", language: "Bahasa" },
    hero: { availability: "Terbuka untuk peluang kerja", intro: "Lulusan baru dari", introAfter: ". Saya membangun aplikasi web full-stack production dan mengintegrasikan sistem AI agentic yang digunakan pengguna nyata, seperti website POS, content agent dengan human approval gate (Telegram), chatbot, dan banyak lagi", viewProjects: "Lihat proyek", getInTouch: "Hubungi saya", projectsFinished: "proyek selesai", providers: "provider LLM terintegrasi", thesis: "validasi skripsi" },
    about: { label: "Tentang", title: "Pola pikir builder, pengalaman operator.", p1: "Setelah mengelola bisnis F&B sejak 2021 hingga sekarang (2026) sambil membangun software, saya memahami bahwa operasional bisnis dan software engineering memiliki prinsip yang sama: ", p1Strong: "rilis, ukur, lalu iterasi.", p2: "Lulusan Teknologi Informasi (IPK 3,56/4,00) dengan kemampuan berpikir analitis dan sistematis. Berpengalaman membangun aplikasi web full-stack serta mengintegrasikan AI/LLM ke sistem production menggunakan Node.js, React, Python, REST API, dan teknologi lainnya. Pembelajar cepat yang adaptif dan mampu mengelola proyek secara mandiri dari konsep hingga deployment. Saya siap berkontribusi sebagai Full-Stack Developer, Web Developer, atau AI Engineer.", p3Before: "Saya berpikir secara sistem. Setiap fitur yang saya bangun adalah fungsi, setiap fungsi adalah alat, dan setiap alat terhubung dengan tindakan nyata. Itulah makna ", p3After: " dalam praktik." },
    projects: { label: "Proyek pilihan", titleBefore: "Solusi praktis,", titleAfter: "dibangun untuk masalah nyata.", allRepos: "semua repo", all: "Semua Proyek", ai: "AI Agent & Otomasi", web: "Pengembangan Web", readMore: "Selengkapnya", viewPicture: "Lihat gambar", photos: "Foto" },
    skills: { label: "Stack", title: "Tools, bukan mainan.", desc: "Teknologi dan framework yang saya gunakan untuk membangun sistem integrasi AI dan aplikasi web yang fungsional untuk menyelesaikan masalah nyata.", tech: "Tech stack", capabilities: "Kemampuan Teknis & Integrasi AI", focus: "Fokus saat ini", focusText: "Membangun autonomous AI agent dengan persetujuan Human-in-the-Loop, pengembangan web, frontend, Structured RAG, dan function calling multi-tool. Saat ini mengeksplorasi orkestrasi multi-agent LangGraph serta mengembangkan otomasi WhatsApp dan POS menjadi workflow AI yang scalable." },
    contact: { label: "Hubungi saya", title: "Ada sistem yang perlu dibangun?", desc: "Terbuka untuk posisi full-time di bidang AI engineering, full-stack development, atau pekerjaan kontrak untuk sistem agentic.", whatsapp: "Chat melalui WhatsApp", or: "atau gunakan formulir berikut", name: "Nama", namePlaceholder: "Nama Anda", email: "Email", message: "Pesan", messagePlaceholder: "Kirim pesan kepada saya...", send: "Kirim pesan", reply: "Dibalas dalam 24 jam · Yogyakarta, GMT+7" },
    modal: { liveDemo: "Demo Langsung", close: "Tutup modal", previous: "Screenshot sebelumnya", next: "Screenshot berikutnya", highlights: "Sorotan & Implementasi:" },
    footer: { description: "Membangun aplikasi web production dan sistem AI agentic. Terbuka untuk peluang kerja.", navigate: "Navigasi", connect: "Terhubung", status: "Terbuka untuk peluang kerja" }
  }
};
